x-service-templates:
  rinhabackend3: &rinhabackend3
    image: rinhabackend3
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RINHA_PORT=8080
      - LOG_LEVEL=DEBUG
      - PROCESSOR_DEFAULT=http://payment-processor-default:8080/
      - PROCESSOR_FALLBACK=http://payment-processor-fallback:8080/
    expose:
      - "8080"
    networks:
      - rinhabackend3
      - payment-processor

services:
  app1:
    <<: *rinhabackend3
    container_name: app1
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "60MB"

  app2:
    <<: *rinhabackend3
    container_name: app2
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "60MB"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-loadbalancer
    ports:
      - "9999:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - rinhabackend3
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

networks:
  rinhabackend3:
    driver: bridge
  payment-processor:
    external: true